Devise
Kolumb555/testguru_1 pull request #11
Opened 2021-05-03 21:44 UTC by Kolumb555

2021-05-04 07:07 UTC, BubuntuClu requested changes

2021-05-04 07:07 UTC, BubuntuClu commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not authorized to view this page.' unless current_user.is_a?(Admin)
добавь метод в модель `User` который будет проверять является ли пользователь админом. `admin?`

2021-05-04 07:07 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +    @test = Test.new(test_params)
у тебя есть ассоциация созданных тестов у пользователя, используй ее вместо костыля ниже

2021-05-04 07:07 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +  def start
старт в админке не нужен

2021-05-04 07:07 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    if resource.is_a?(Admin)
`resource.admin?`

2021-05-04 07:07 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
тебе этот контроллер больше не нужен

2021-05-04 07:07 UTC, BubuntuClu commented on app/controllers/replies_controller.rb
>  class RepliesController < ApplicationController
и этот тоже

2021-05-08 13:54 UTC, Kolumb555 commented on app/controllers/application_controller.rb
> +    if resource.is_a?(Admin)
Если определяю метод admin? в модели юзер, в этом контроллере он не работает.

2021-05-08 18:57 UTC, BubuntuClu requested changes

2021-05-08 18:57 UTC, BubuntuClu commented on app/models/user.rb
> +    current_user.is_a?(Admin)
это не будет работать. у тебя `current_user` и есть пользователь.

2021-05-08 18:57 UTC, BubuntuClu commented on app/models/user.rb
> +  def admin?
метод добавил, а его использование нет

2021-05-08 19:34 UTC, Kolumb555 commented on app/models/user.rb
> +  def admin?
Добавил метод в ApplicationController - тогда он работает в Admin::BaseController

2021-05-09 07:00 UTC, BubuntuClu requested changes

2021-05-09 07:00 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def admin?
self здесь будет контроллер, а не пользователь. тебе пользователя надо проверить, что он админ.

2021-05-09 07:00 UTC, BubuntuClu commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not authorized to view this page.' unless admin?
метод инстанса сделать надо, в модели пользователя.

2021-05-09 07:00 UTC, BubuntuClu commented on app/models/user.rb
> -  def admin?
зря убрал

2021-05-09 17:49 UTC, BubuntuClu approved these changes

2021-05-09 17:49 UTC, BubuntuClu commented on app/models/user.rb
> +  def admin?
тебе метод нужен для модели, а не для контроллера

2021-05-12 18:30 UTC, merged