Deploy
Kolumb555/testguru_1 pull request #19
Opened 2022-04-30 18:52 UTC by Kolumb555

2022-05-01 18:37 UTC, BubuntuClu commented on db/migrate/20220425141222_create_feedbacks.rb
> +  def self.up
тут нет смысла в двух отдельных методах, зватит и `change`

2022-05-05 07:10 UTC, BubuntuClu requested changes

2022-05-05 07:10 UTC, BubuntuClu commented on db/migrate/20210130172036_create_questions.rb
> +      t.references :test, index: true, foreign_key: {on_delete: :cascade}
подобного поведения можно достичь еще используя опцию `dependent: destroy` на ассоциациях. ее для текущего задания достаточно.

а по самой миграции ты сделал не совсем правильно, так как правишь уже существующие миграции. правильно, это удалить внешние ключи в таблицах и добавить новые с каскадным удалением

2022-05-05 07:10 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    if @test.questions.any?
это тоже костыль)
автор задумал 10 вопросов, после добавления первого вопроса тест сразу же появится в списке, у вопроса даже может не быть еще ответов, а пользователь сможет начать его проходить.

самый лучший вариант в данной ситуации, оставить публикацию теста на плечах автора, когда он сам решит что тест готов к публикации, тогда и показывать тест в списке доступных для прохождения

2022-05-05 16:25 UTC, Kolumb555 commented on app/controllers/tests_controller.rb
> +    if @test.questions.any?
Тогда необходимо добавить модели Тест свойство "публиковать" с false по умолчанию - и пока автор не изменит на true - не публиковать этот тест для прохождения?

2022-05-11 16:31 UTC, merged