badge 1.0
Kolumb555/testguru_1 pull request #20
Opened 2022-05-17 19:29 UTC by Kolumb555

2022-05-18 06:16 UTC, BubuntuClu requested changes

2022-05-18 06:16 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.passed = test_passed?
этот метод только ответы считает, он не должен делать ничего другого. вынести надо этот код из этого метода

2022-05-18 06:16 UTC, BubuntuClu commented on app/services/award_give_service.rb
> +  def category_rule
добавь параметры для методов проверок. чтобы только определенные категории награждались, а не все подряд. параметр можно хранить в самом бадже

2022-05-18 06:16 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      @badges = AwardGiveService.new(@test_passage).call
вызывать сервис стоит только при успешном прохождении теста

2022-05-18 06:16 UTC, BubuntuClu commented on app/services/award_give_service.rb
> +  def level_rule
тут будет параметр уровня в бадже

2022-05-18 06:16 UTC, BubuntuClu commented on app/services/award_give_service.rb
> +  def first_try_rule
тут будет пустой параметр

2022-05-21 18:02 UTC, BubuntuClu commented on app/javascript/utilities/new_badge.js
> +    if (rule_chosen === "category") {
1 - esle if плохая конструкция. лучше переделай ее на if+return
2 - при добавлении нового правила у тебя будет расширятся этот метод. надо бы что-то придумать

2022-05-21 18:02 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    test_passage_passed?
от того что ты вынес это в отдельный метод, сути проблемы это не меняет. метод `accept!` должен только принимать ответы. устанавливать прохождение ты должен в другом месте, не в этом методе

2022-05-21 18:02 UTC, BubuntuClu commented on db/migrate/20220518131350_add_rule_option_to_badges.rb
> +class AddRuleOptionToBadges < ActiveRecord::Migration[6.1]
этой миграции не должно быть. ты локально работаешь с веткой, ее еще ни у кого нет, ты можешь откатывать миграции без последствий. откати миграцию создани ятаблицы баджей и добавь туда нужные строки. так у тебя не будет кучи ненужных миграций

2022-05-26 14:01 UTC, Kolumb555 commented on app/models/test_passage.rb
> +    test_passage_passed?
так и не удалось понять, куда этот метод перенести можно

2022-05-26 14:08 UTC, merged